package:
    name: gitutils
    version: 1.4
source:
    path: ..
requirements:
    build:
        - python
        - setuptools
    run:
        - python

build:
  entry_points:
    - gitutils = gitutils.gitutils:main

about:
    home: https://git.psi.ch/controls_highlevel_applications/app_config
    summary: "GITUTILS is a tool to facilitate the server-side operations when developing software that uses git repositories."
