package:
    name: gitutils
    version: 1.0.1
source:
    path: ..
requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - python-gitlab

build:
  noarch: python
  number: 6
  entry_points:
    - gitutils = gitutils.gitutils:main

about:
    home: https://git.psi.ch/controls_highlevel_applications/ch.psi.gitutils
    summary: "GITUTILS is a tool to facilitate the server-side operations when developing software that uses git repositories."
