package:
    name: gitutils
    version: "{{ load_setup_py_data().version }}"
source:
    path: ..
requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - python-gitlab

build:
  noarch: python
  number: 1
  entry_points:
    - gitutils = gitutils.gitutils:main

about:
    home: https://github.com/paulscherrerinstitute/gitutils
    summary: "GITUTILS is a tool to facilitate the server-side operations when developing software that uses git repositories."
