{% set name = "python-gitlab" %}
{% set version = "1.10.0" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "c4e91b9367c54c3049d702c35dd966f9e5a8989dae1be56ef7a1c35c2b235a58" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  noarch: python
  number: 0
  entry_points:
    - gitlab = gitlab.cli:main
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
    - setuptools
    - requests >=2.4.2
    - six
  run:
    - python
    - requests >=2.4.2
    - six

test:
  imports:
    - gitlab
    - gitlab.tests
    - gitlab.v4
  commands:
    - gitlab --help

about:
  home: https://github.com/python-gitlab/python-gitlab
  license: GNU Lesser General Public License v3 (LGPLv3)
  license_family: LGPL
  license_file: ''
  summary: Interact with GitLab API
  description: ".. image:: https://travis-ci.org/python-gitlab/python-gitlab.svg?branch=master\n   :target: https://travis-ci.org/python-gitlab/python-gitlab\n\n.. image:: https://badge.fury.io/py/python-gitlab.svg\n\
    \   :target: https://badge.fury.io/py/python-gitlab\n\n.. image:: https://readthedocs.org/projects/python-gitlab/badge/?version=latest\n   :target: https://python-gitlab.readthedocs.org/en/latest/?badge=latest\n\
    \n.. image:: https://img.shields.io/pypi/pyversions/python-gitlab.svg\n   :target: https://pypi.python.org/pypi/python-gitlab\n\n.. image:: https://img.shields.io/gitter/room/python-gitlab/Lobby.svg\n\
    \   :target: https://gitter.im/python-gitlab/Lobby\n\n.. image:: https://img.shields.io/badge/code%20style-black-000000.svg\n    :target: https://github.com/python/black\n\nPython GitLab\n=============\n\
    \n``python-gitlab`` is a Python package providing access to the GitLab server API.\n\nIt supports the v4 API of GitLab, and provides a CLI tool (``gitlab``).\n\nInstallation\n============\n\nRequirements\n\
    ------------\n\npython-gitlab depends on:\n\n* `python-requests <http://docs.python-requests.org/en/latest/>`_\n* `six <https://six.readthedocs.io/>`_\n\nInstall with pip\n----------------\n\n.. code-block::\
    \ console\n\n   pip install python-gitlab\n\n\nUsing the python-gitlab docker image\n====================================\n\nHow to build\n------------\n\n``docker build -t python-gitlab:TAG .``\n\n\
    How to use\n----------\n\n``docker run -it --rm -e GITLAB_PRIVATE_TOKEN=<your token> -v /path/to/python-gitlab.cfg:/python-gitlab.cfg python-gitlab <command> ...``\n\nor run it directly from the upstream\
    \ image:\n\n``docker run -it --rm -e GITLAB_PRIVATE_TOKEN=<your token> -v /path/to/python-gitlab.cfg:/python-gitlab.cfg registry.gitlab.com/python-gitlab/python-gitlab:v1.8.0 <command> ...``\n\nTo change\
    \ the GitLab URL, use `-e GITLAB_URL=<your url>`\n\nBring your own config file:\n``docker run -it --rm -v /path/to/python-gitlab.cfg:/python-gitlab.cfg -e GITLAB_CFG=/python-gitlab.cfg python-gitlab\
    \ <command> ...``\n\n\nBug reports\n===========\n\nPlease report bugs and feature requests at\nhttps://github.com/python-gitlab/python-gitlab/issues.\n\n\nDocumentation\n=============\n\nThe full documentation\
    \ for CLI and API is available on `readthedocs\n<http://python-gitlab.readthedocs.org/en/stable/>`_.\n\nBuild the docs\n--------------\nYou can build the documentation using ``sphinx``::\n\n    pip\
    \ install sphinx\n    python setup.py build_sphinx\n\n\nContributing\n============\n\nYou can contribute to the project in multiple ways:\n\n* Write documentation\n* Implement features\n* Fix bugs\n\
    * Add unit and functional tests\n* Everything else you can think of\n\nWe enforce commit messages to be formatted using the `conventional-changelog <https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines>`_.\n\
    This leads to more readable messages that are easy to follow when looking through the project history.\n\nPlease provide your patches as github pull requests. Thanks!\n\nCode-Style\n----------\n\nWe\
    \ use black as code formatter, so you'll need to format your changes using the\n`black code formatter\n<https://github.com/python/black>`_.\n\nJust run\n\n.. code-block:: bash\n\n  cd python-gitlab/\n\
    \  pip3 install --user black\n  black .\n\nto format your code according to our guidelines.\n\nRunning unit tests\n------------------\n\nBefore submitting a pull request make sure that the tests still\
    \ succeed with\nyour change. Unit tests and functional tests run using the travis service and\npassing tests are mandatory to get merge requests accepted.\n\nYou need to install ``tox`` to run unit\
    \ tests and documentation builds locally:\n\n.. code-block:: bash\n\n   # run the unit tests for python 2/3, and the pep8 tests:\n   tox\n\n   # run tests in one environment only:\n   tox -epy35\n\n\
    \   # build the documentation, the result will be generated in\n   # build/sphinx/html/\n   tox -edocs\n\nRunning integration tests\n-------------------------\n\nTwo scripts run tests against a running\
    \ gitlab instance, using a docker\ncontainer. You need to have docker installed on the test machine, and your user\nmust have the correct permissions to talk to the docker daemon.\n\nTo run these tests:\n\
    \n.. code-block:: bash\n\n   # run the CLI tests:\n   ./tools/functional_tests.sh\n\n   # run the python API tests:\n   ./tools/py_functional_tests.sh\n\nYou can also build a test environment using\
    \ the following command:\n\n.. code-block:: bash\n\n   ./tools/build_test_env.sh\n\nA freshly configured gitlab container will be available at\nhttp://localhost:8080 (login ``root`` / password ``5iveL!fe``).\
    \ A configuration\nfor python-gitlab will be written in ``/tmp/python-gitlab.cfg``.\n\nTo cleanup the environment delete the container:\n\n.. code-block:: bash\n\n   docker rm -f gitlab-test\n\n\n"
  doc_url: ''
  dev_url: ''

extra:
  recipe-maintainers: ''
