name: conda_publish

on:
  release:
    types: [published]
  workflow_dispatch:


jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests 
        run: python -m unittest gitutils.tests.gitutils_unittest 
        run: python -m unittest gitutils.tests.gitutils_cmds
    - name: publish-to-conda
      uses: paulscherrerinstitute/conda-publish-action@master
      with:
        subdir: 'conda-recipe'
        anacondatoken: ${{ secrets.ANACONDA_TOKEN }}
        packagename: 'gitutils'
