name: unit & behavior tests

on:
  workflow_dispatch:


jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]    # [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6]  # [3.6, 3.7, 3.8, pypy3]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Run unit tests
        run: python unittest gitutils/tests/gitutils_unittest.py
      - name: Run cmd behavior tests
        run: python unittest gitutils/tests/gitutils_cmds.py
