name: unit tests

on:
  workflow_dispatch:


jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run unit tests
        run: python -m unittest gitutils.tests.gitutils_unittest 
    - name: Run cmd behavior tests
        run: python -m unittest gitutils.tests.gitutils_cmds
